//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MarvelApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MarvelApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvelSharp.MarvelApiResources", typeof(MarvelApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastWeek.
        /// </summary>
        public static string DateDescriptorLastWeek {
            get {
                return ResourceManager.GetString("DateDescriptorLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nextWeek.
        /// </summary>
        public static string DateDescriptorNextWeek {
            get {
                return ResourceManager.GetString("DateDescriptorNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thisMonth.
        /// </summary>
        public static string DateDescriptorThisMonth {
            get {
                return ResourceManager.GetString("DateDescriptorThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thisWeek.
        /// </summary>
        public static string DateDescriptorThisWeek {
            get {
                return ResourceManager.GetString("DateDescriptorThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comic.
        /// </summary>
        public static string FormatComic {
            get {
                return ResourceManager.GetString("FormatComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digest.
        /// </summary>
        public static string FormatDigest {
            get {
                return ResourceManager.GetString("FormatDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digital comic.
        /// </summary>
        public static string FormatDigitalComic {
            get {
                return ResourceManager.GetString("FormatDigitalComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphic novel.
        /// </summary>
        public static string FormatGraphicNovel {
            get {
                return ResourceManager.GetString("FormatGraphicNovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hardcover.
        /// </summary>
        public static string FormatHardcover {
            get {
                return ResourceManager.GetString("FormatHardcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infinite comic.
        /// </summary>
        public static string FormatInfiniteComic {
            get {
                return ResourceManager.GetString("FormatInfiniteComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magazine.
        /// </summary>
        public static string FormatMagazine {
            get {
                return ResourceManager.GetString("FormatMagazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trade paperback.
        /// </summary>
        public static string FormatTradePaperback {
            get {
                return ResourceManager.GetString("FormatTradePaperback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection.
        /// </summary>
        public static string FormatTypeCollection {
            get {
                return ResourceManager.GetString("FormatTypeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comic.
        /// </summary>
        public static string FormatTypeComic {
            get {
                return ResourceManager.GetString("FormatTypeComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string HttpSuccessCode {
            get {
                return ResourceManager.GetString("HttpSuccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        public static string OrderByDateModifiedAsc {
            get {
                return ResourceManager.GetString("OrderByDateModifiedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -modified.
        /// </summary>
        public static string OrderByDateModifiedDesc {
            get {
                return ResourceManager.GetString("OrderByDateModifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstName.
        /// </summary>
        public static string OrderByFirstNameAsc {
            get {
                return ResourceManager.GetString("OrderByFirstNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -firstName.
        /// </summary>
        public static string OrderByFirstNameDesc {
            get {
                return ResourceManager.GetString("OrderByFirstNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to focDate.
        /// </summary>
        public static string OrderByFocDateAsc {
            get {
                return ResourceManager.GetString("OrderByFocDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -focDate.
        /// </summary>
        public static string OrderByFocDateDesc {
            get {
                return ResourceManager.GetString("OrderByFocDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string OrderByIdAsc {
            get {
                return ResourceManager.GetString("OrderByIdAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -id.
        /// </summary>
        public static string OrderByIdDesc {
            get {
                return ResourceManager.GetString("OrderByIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issueNumber.
        /// </summary>
        public static string OrderByIssueNoAsc {
            get {
                return ResourceManager.GetString("OrderByIssueNoAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -issueNumber.
        /// </summary>
        public static string OrderByIssueNoDesc {
            get {
                return ResourceManager.GetString("OrderByIssueNoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastName.
        /// </summary>
        public static string OrderByLastNameAsc {
            get {
                return ResourceManager.GetString("OrderByLastNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -lastName.
        /// </summary>
        public static string OrderByLastNameDesc {
            get {
                return ResourceManager.GetString("OrderByLastNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleName.
        /// </summary>
        public static string OrderByMiddleNameAsc {
            get {
                return ResourceManager.GetString("OrderByMiddleNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -middleName.
        /// </summary>
        public static string OrderByMiddleNameDesc {
            get {
                return ResourceManager.GetString("OrderByMiddleNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string OrderByNameAsc {
            get {
                return ResourceManager.GetString("OrderByNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -name.
        /// </summary>
        public static string OrderByNameDesc {
            get {
                return ResourceManager.GetString("OrderByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onsaleDate.
        /// </summary>
        public static string OrderByOnSaleDateAsc {
            get {
                return ResourceManager.GetString("OrderByOnSaleDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -onsaleDate.
        /// </summary>
        public static string OrderByOnSaleDateDesc {
            get {
                return ResourceManager.GetString("OrderByOnSaleDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startDate.
        /// </summary>
        public static string OrderByStartDateAsc {
            get {
                return ResourceManager.GetString("OrderByStartDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -startDate.
        /// </summary>
        public static string OrderByStartDateDesc {
            get {
                return ResourceManager.GetString("OrderByStartDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startYear.
        /// </summary>
        public static string OrderByStartYearAsc {
            get {
                return ResourceManager.GetString("OrderByStartYearAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -startYear.
        /// </summary>
        public static string OrderByStartYearDesc {
            get {
                return ResourceManager.GetString("OrderByStartYearDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix.
        /// </summary>
        public static string OrderBySuffixAsc {
            get {
                return ResourceManager.GetString("OrderBySuffixAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -suffix.
        /// </summary>
        public static string OrderBySuffixDesc {
            get {
                return ResourceManager.GetString("OrderBySuffixDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string OrderByTitleAsc {
            get {
                return ResourceManager.GetString("OrderByTitleAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -title.
        /// </summary>
        public static string OrderByTitleDesc {
            get {
                return ResourceManager.GetString("OrderByTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apikey.
        /// </summary>
        public static string ParameterApiKey {
            get {
                return ResourceManager.GetString("ParameterApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string ParameterCharacters {
            get {
                return ResourceManager.GetString("ParameterCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collaborators.
        /// </summary>
        public static string ParameterCollaborators {
            get {
                return ResourceManager.GetString("ParameterCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics.
        /// </summary>
        public static string ParameterComics {
            get {
                return ResourceManager.GetString("ParameterComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string ParameterContains {
            get {
                return ResourceManager.GetString("ParameterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators.
        /// </summary>
        public static string ParameterCreators {
            get {
                return ResourceManager.GetString("ParameterCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateDescriptor.
        /// </summary>
        public static string ParameterDateDescriptor {
            get {
                return ResourceManager.GetString("ParameterDateDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateRange.
        /// </summary>
        public static string ParameterDateRange {
            get {
                return ResourceManager.GetString("ParameterDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string ParameterDateTimeFormat {
            get {
                return ResourceManager.GetString("ParameterDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diamondCode.
        /// </summary>
        public static string ParameterDiamondCode {
            get {
                return ResourceManager.GetString("ParameterDiamondCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digitalId.
        /// </summary>
        public static string ParameterDigitalId {
            get {
                return ResourceManager.GetString("ParameterDigitalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ean.
        /// </summary>
        public static string ParameterEan {
            get {
                return ResourceManager.GetString("ParameterEan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string ParameterEvents {
            get {
                return ResourceManager.GetString("ParameterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstName.
        /// </summary>
        public static string ParameterFirstName {
            get {
                return ResourceManager.GetString("ParameterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstNameStartsWith.
        /// </summary>
        public static string ParameterFirstNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterFirstNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        public static string ParameterFormat {
            get {
                return ResourceManager.GetString("ParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatType.
        /// </summary>
        public static string ParameterFormatType {
            get {
                return ResourceManager.GetString("ParameterFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDigitalIssue.
        /// </summary>
        public static string ParameterHasDigitalIssue {
            get {
                return ResourceManager.GetString("ParameterHasDigitalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash.
        /// </summary>
        public static string ParameterHash {
            get {
                return ResourceManager.GetString("ParameterHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isbn.
        /// </summary>
        public static string ParameterIsbn {
            get {
                return ResourceManager.GetString("ParameterIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issn.
        /// </summary>
        public static string ParameterIssn {
            get {
                return ResourceManager.GetString("ParameterIssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issueNumber.
        /// </summary>
        public static string ParameterIssueNumber {
            get {
                return ResourceManager.GetString("ParameterIssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastName.
        /// </summary>
        public static string ParameterLastName {
            get {
                return ResourceManager.GetString("ParameterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastNameStartsWith.
        /// </summary>
        public static string ParameterLastNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterLastNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        public static string ParameterLimit {
            get {
                return ResourceManager.GetString("ParameterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string ParameterListSeparator {
            get {
                return ResourceManager.GetString("ParameterListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleName.
        /// </summary>
        public static string ParameterMiddleName {
            get {
                return ResourceManager.GetString("ParameterMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleNameStartsWith.
        /// </summary>
        public static string ParameterMiddleNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterMiddleNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifiedSince.
        /// </summary>
        public static string ParameterModifiedSince {
            get {
                return ResourceManager.GetString("ParameterModifiedSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nameStartsWith.
        /// </summary>
        public static string ParameterNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noVariants.
        /// </summary>
        public static string ParameterNoVariants {
            get {
                return ResourceManager.GetString("ParameterNoVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        public static string ParameterOffset {
            get {
                return ResourceManager.GetString("ParameterOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderBy.
        /// </summary>
        public static string ParameterOrderBy {
            get {
                return ResourceManager.GetString("ParameterOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        public static string ParameterSeries {
            get {
                return ResourceManager.GetString("ParameterSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seriesType.
        /// </summary>
        public static string ParameterSeriesType {
            get {
                return ResourceManager.GetString("ParameterSeriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharedAppearances.
        /// </summary>
        public static string ParameterSharedAppearances {
            get {
                return ResourceManager.GetString("ParameterSharedAppearances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startYear.
        /// </summary>
        public static string ParameterStartYear {
            get {
                return ResourceManager.GetString("ParameterStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories.
        /// </summary>
        public static string ParameterStories {
            get {
                return ResourceManager.GetString("ParameterStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix.
        /// </summary>
        public static string ParameterSuffix {
            get {
                return ResourceManager.GetString("ParameterSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ts.
        /// </summary>
        public static string ParameterTimeStamp {
            get {
                return ResourceManager.GetString("ParameterTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyMMddHHmmss.
        /// </summary>
        public static string ParameterTimeStampFormat {
            get {
                return ResourceManager.GetString("ParameterTimeStampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string ParameterTitle {
            get {
                return ResourceManager.GetString("ParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titleStartsWith.
        /// </summary>
        public static string ParameterTitleStartsWith {
            get {
                return ResourceManager.GetString("ParameterTitleStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upc.
        /// </summary>
        public static string ParameterUpc {
            get {
                return ResourceManager.GetString("ParameterUpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string ParameterValueFalse {
            get {
                return ResourceManager.GetString("ParameterValueFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string ParameterValueTrue {
            get {
                return ResourceManager.GetString("ParameterValueTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection.
        /// </summary>
        public static string SeriesTypeCollection {
            get {
                return ResourceManager.GetString("SeriesTypeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limited.
        /// </summary>
        public static string SeriesTypeLimited {
            get {
                return ResourceManager.GetString("SeriesTypeLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one shot.
        /// </summary>
        public static string SeriesTypeOneShot {
            get {
                return ResourceManager.GetString("SeriesTypeOneShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ongoing.
        /// </summary>
        public static string SeriesTypeOngoing {
            get {
                return ResourceManager.GetString("SeriesTypeOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateway.marvel.com/v1/public/.
        /// </summary>
        public static string UrlBase {
            get {
                return ResourceManager.GetString("UrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string UrlSuffixAllCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixAllCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics.
        /// </summary>
        public static string UrlSuffixAllComics {
            get {
                return ResourceManager.GetString("UrlSuffixAllComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators.
        /// </summary>
        public static string UrlSuffixAllCreators {
            get {
                return ResourceManager.GetString("UrlSuffixAllCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string UrlSuffixAllEvents {
            get {
                return ResourceManager.GetString("UrlSuffixAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        public static string UrlSuffixAllSeries {
            get {
                return ResourceManager.GetString("UrlSuffixAllSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        public static string UrlSuffixAllStories {
            get {
                return ResourceManager.GetString("UrlSuffixAllStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}.
        /// </summary>
        public static string UrlSuffixCharacterById {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/comics.
        /// </summary>
        public static string UrlSuffixCharacterComics {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/events.
        /// </summary>
        public static string UrlSuffixCharacterEvents {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/series.
        /// </summary>
        public static string UrlSuffixCharacterSeries {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/stories.
        /// </summary>
        public static string UrlSuffixCharacterStories {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}.
        /// </summary>
        public static string UrlSuffixComicById {
            get {
                return ResourceManager.GetString("UrlSuffixComicById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/characters.
        /// </summary>
        public static string UrlSuffixComicCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixComicCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/creators.
        /// </summary>
        public static string UrlSuffixComicCreators {
            get {
                return ResourceManager.GetString("UrlSuffixComicCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/events.
        /// </summary>
        public static string UrlSuffixComicEvents {
            get {
                return ResourceManager.GetString("UrlSuffixComicEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/stories.
        /// </summary>
        public static string UrlSuffixComicStories {
            get {
                return ResourceManager.GetString("UrlSuffixComicStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}.
        /// </summary>
        public static string UrlSuffixCreatorById {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/comics.
        /// </summary>
        public static string UrlSuffixCreatorComics {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/events.
        /// </summary>
        public static string UrlSuffixCreatorEvents {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/series.
        /// </summary>
        public static string UrlSuffixCreatorSeries {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/stories.
        /// </summary>
        public static string UrlSuffixCreatorStories {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}.
        /// </summary>
        public static string UrlSuffixEventById {
            get {
                return ResourceManager.GetString("UrlSuffixEventById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/characters.
        /// </summary>
        public static string UrlSuffixEventCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixEventCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/comics.
        /// </summary>
        public static string UrlSuffixEventComics {
            get {
                return ResourceManager.GetString("UrlSuffixEventComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/creators.
        /// </summary>
        public static string UrlSuffixEventCreators {
            get {
                return ResourceManager.GetString("UrlSuffixEventCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/series.
        /// </summary>
        public static string UrlSuffixEventSeries {
            get {
                return ResourceManager.GetString("UrlSuffixEventSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/stories.
        /// </summary>
        public static string UrlSuffixEventStories {
            get {
                return ResourceManager.GetString("UrlSuffixEventStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}.
        /// </summary>
        public static string UrlSuffixSeriesById {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/characters.
        /// </summary>
        public static string UrlSuffixSeriesCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/comics.
        /// </summary>
        public static string UrlSuffixSeriesComics {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/creators.
        /// </summary>
        public static string UrlSuffixSeriesCreators {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/events.
        /// </summary>
        public static string UrlSuffixSeriesEvents {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/stories.
        /// </summary>
        public static string UrlSuffixSeriesStories {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}.
        /// </summary>
        public static string UrlSuffixStoryById {
            get {
                return ResourceManager.GetString("UrlSuffixStoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/characters.
        /// </summary>
        public static string UrlSuffixStoryCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixStoryCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/comics.
        /// </summary>
        public static string UrlSuffixStoryComics {
            get {
                return ResourceManager.GetString("UrlSuffixStoryComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/creators.
        /// </summary>
        public static string UrlSuffixStoryCreators {
            get {
                return ResourceManager.GetString("UrlSuffixStoryCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/events.
        /// </summary>
        public static string UrlSuffixStoryEvents {
            get {
                return ResourceManager.GetString("UrlSuffixStoryEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/series.
        /// </summary>
        public static string UrlSuffixStorySeries {
            get {
                return ResourceManager.GetString("UrlSuffixStorySeries", resourceCulture);
            }
        }
    }
}
