//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarvelApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarvelApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvelSharp.MarvelApiResources", typeof(MarvelApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string HttpSuccessCode {
            get {
                return ResourceManager.GetString("HttpSuccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apikey.
        /// </summary>
        internal static string ParameterApiKey {
            get {
                return ResourceManager.GetString("ParameterApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        internal static string ParameterCharacters {
            get {
                return ResourceManager.GetString("ParameterCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collaborators.
        /// </summary>
        internal static string ParameterCollaborators {
            get {
                return ResourceManager.GetString("ParameterCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics.
        /// </summary>
        internal static string ParameterComics {
            get {
                return ResourceManager.GetString("ParameterComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string ParameterContains {
            get {
                return ResourceManager.GetString("ParameterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators.
        /// </summary>
        internal static string ParameterCreators {
            get {
                return ResourceManager.GetString("ParameterCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateDescriptor.
        /// </summary>
        internal static string ParameterDateDescriptor {
            get {
                return ResourceManager.GetString("ParameterDateDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateRange.
        /// </summary>
        internal static string ParameterDateRange {
            get {
                return ResourceManager.GetString("ParameterDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string ParameterDateTimeFormat {
            get {
                return ResourceManager.GetString("ParameterDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diamondCode.
        /// </summary>
        internal static string ParameterDiamondCode {
            get {
                return ResourceManager.GetString("ParameterDiamondCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digitalId.
        /// </summary>
        internal static string ParameterDigitalId {
            get {
                return ResourceManager.GetString("ParameterDigitalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ean.
        /// </summary>
        internal static string ParameterEan {
            get {
                return ResourceManager.GetString("ParameterEan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string ParameterEvents {
            get {
                return ResourceManager.GetString("ParameterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstName.
        /// </summary>
        internal static string ParameterFirstName {
            get {
                return ResourceManager.GetString("ParameterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstNameStartsWith.
        /// </summary>
        internal static string ParameterFirstNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterFirstNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        internal static string ParameterFormat {
            get {
                return ResourceManager.GetString("ParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatType.
        /// </summary>
        internal static string ParameterFormatType {
            get {
                return ResourceManager.GetString("ParameterFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasDigitalIssue.
        /// </summary>
        internal static string ParameterHasDigitalIssue {
            get {
                return ResourceManager.GetString("ParameterHasDigitalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash.
        /// </summary>
        internal static string ParameterHash {
            get {
                return ResourceManager.GetString("ParameterHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isbn.
        /// </summary>
        internal static string ParameterIsbn {
            get {
                return ResourceManager.GetString("ParameterIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issn.
        /// </summary>
        internal static string ParameterIssn {
            get {
                return ResourceManager.GetString("ParameterIssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issueNumber.
        /// </summary>
        internal static string ParameterIssueNumber {
            get {
                return ResourceManager.GetString("ParameterIssueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastName.
        /// </summary>
        internal static string ParameterLastName {
            get {
                return ResourceManager.GetString("ParameterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastNameStartsWith.
        /// </summary>
        internal static string ParameterLastNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterLastNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit.
        /// </summary>
        internal static string ParameterLimit {
            get {
                return ResourceManager.GetString("ParameterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ParameterListSeparator {
            get {
                return ResourceManager.GetString("ParameterListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleName.
        /// </summary>
        internal static string ParameterMiddleName {
            get {
                return ResourceManager.GetString("ParameterMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleNameStartsWith.
        /// </summary>
        internal static string ParameterMiddleNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterMiddleNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifiedSince.
        /// </summary>
        internal static string ParameterModifiedSince {
            get {
                return ResourceManager.GetString("ParameterModifiedSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nameStartsWith.
        /// </summary>
        internal static string ParameterNameStartsWith {
            get {
                return ResourceManager.GetString("ParameterNameStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noVariants.
        /// </summary>
        internal static string ParameterNoVariants {
            get {
                return ResourceManager.GetString("ParameterNoVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string ParameterOffset {
            get {
                return ResourceManager.GetString("ParameterOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orderBy.
        /// </summary>
        internal static string ParameterOrderBy {
            get {
                return ResourceManager.GetString("ParameterOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string ParameterSeries {
            get {
                return ResourceManager.GetString("ParameterSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seriesType.
        /// </summary>
        internal static string ParameterSeriesType {
            get {
                return ResourceManager.GetString("ParameterSeriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharedAppearances.
        /// </summary>
        internal static string ParameterSharedAppearances {
            get {
                return ResourceManager.GetString("ParameterSharedAppearances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startYear.
        /// </summary>
        internal static string ParameterStartYear {
            get {
                return ResourceManager.GetString("ParameterStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories.
        /// </summary>
        internal static string ParameterStories {
            get {
                return ResourceManager.GetString("ParameterStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix.
        /// </summary>
        internal static string ParameterSuffix {
            get {
                return ResourceManager.GetString("ParameterSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ts.
        /// </summary>
        internal static string ParameterTimeStamp {
            get {
                return ResourceManager.GetString("ParameterTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyMMddHHmmss.
        /// </summary>
        internal static string ParameterTimeStampFormat {
            get {
                return ResourceManager.GetString("ParameterTimeStampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string ParameterTitle {
            get {
                return ResourceManager.GetString("ParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titleStartsWith.
        /// </summary>
        internal static string ParameterTitleStartsWith {
            get {
                return ResourceManager.GetString("ParameterTitleStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upc.
        /// </summary>
        internal static string ParameterUpc {
            get {
                return ResourceManager.GetString("ParameterUpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string ParameterValueFalse {
            get {
                return ResourceManager.GetString("ParameterValueFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ParameterValueTrue {
            get {
                return ResourceManager.GetString("ParameterValueTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gateway.marvel.com/v1/public/.
        /// </summary>
        internal static string UrlBase {
            get {
                return ResourceManager.GetString("UrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        internal static string UrlSuffixAllCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixAllCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics.
        /// </summary>
        internal static string UrlSuffixAllComics {
            get {
                return ResourceManager.GetString("UrlSuffixAllComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators.
        /// </summary>
        internal static string UrlSuffixAllCreators {
            get {
                return ResourceManager.GetString("UrlSuffixAllCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string UrlSuffixAllEvents {
            get {
                return ResourceManager.GetString("UrlSuffixAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string UrlSuffixAllSeries {
            get {
                return ResourceManager.GetString("UrlSuffixAllSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string UrlSuffixAllStories {
            get {
                return ResourceManager.GetString("UrlSuffixAllStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}.
        /// </summary>
        internal static string UrlSuffixCharacterById {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/comics.
        /// </summary>
        internal static string UrlSuffixCharacterComics {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/events.
        /// </summary>
        internal static string UrlSuffixCharacterEvents {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/series.
        /// </summary>
        internal static string UrlSuffixCharacterSeries {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters/{0}/stories.
        /// </summary>
        internal static string UrlSuffixCharacterStories {
            get {
                return ResourceManager.GetString("UrlSuffixCharacterStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}.
        /// </summary>
        internal static string UrlSuffixComicById {
            get {
                return ResourceManager.GetString("UrlSuffixComicById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/characters.
        /// </summary>
        internal static string UrlSuffixComicCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixComicCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/creators.
        /// </summary>
        internal static string UrlSuffixComicCreators {
            get {
                return ResourceManager.GetString("UrlSuffixComicCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/events.
        /// </summary>
        internal static string UrlSuffixComicEvents {
            get {
                return ResourceManager.GetString("UrlSuffixComicEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comics/{0}/stories.
        /// </summary>
        internal static string UrlSuffixComicStories {
            get {
                return ResourceManager.GetString("UrlSuffixComicStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}.
        /// </summary>
        internal static string UrlSuffixCreatorById {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/comics.
        /// </summary>
        internal static string UrlSuffixCreatorComics {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/events.
        /// </summary>
        internal static string UrlSuffixCreatorEvents {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/series.
        /// </summary>
        internal static string UrlSuffixCreatorSeries {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creators/{0}/stories.
        /// </summary>
        internal static string UrlSuffixCreatorStories {
            get {
                return ResourceManager.GetString("UrlSuffixCreatorStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}.
        /// </summary>
        internal static string UrlSuffixEventById {
            get {
                return ResourceManager.GetString("UrlSuffixEventById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/characters.
        /// </summary>
        internal static string UrlSuffixEventCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixEventCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/comics.
        /// </summary>
        internal static string UrlSuffixEventComics {
            get {
                return ResourceManager.GetString("UrlSuffixEventComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/creators.
        /// </summary>
        internal static string UrlSuffixEventCreators {
            get {
                return ResourceManager.GetString("UrlSuffixEventCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/series.
        /// </summary>
        internal static string UrlSuffixEventSeries {
            get {
                return ResourceManager.GetString("UrlSuffixEventSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events/{0}/stories.
        /// </summary>
        internal static string UrlSuffixEventStories {
            get {
                return ResourceManager.GetString("UrlSuffixEventStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}.
        /// </summary>
        internal static string UrlSuffixSeriesById {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/characters.
        /// </summary>
        internal static string UrlSuffixSeriesCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/comics.
        /// </summary>
        internal static string UrlSuffixSeriesComics {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/creators.
        /// </summary>
        internal static string UrlSuffixSeriesCreators {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/events.
        /// </summary>
        internal static string UrlSuffixSeriesEvents {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series/{0}/stories.
        /// </summary>
        internal static string UrlSuffixSeriesStories {
            get {
                return ResourceManager.GetString("UrlSuffixSeriesStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}.
        /// </summary>
        internal static string UrlSuffixStoryById {
            get {
                return ResourceManager.GetString("UrlSuffixStoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/characters.
        /// </summary>
        internal static string UrlSuffixStoryCharacters {
            get {
                return ResourceManager.GetString("UrlSuffixStoryCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/comics.
        /// </summary>
        internal static string UrlSuffixStoryComics {
            get {
                return ResourceManager.GetString("UrlSuffixStoryComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/creators.
        /// </summary>
        internal static string UrlSuffixStoryCreators {
            get {
                return ResourceManager.GetString("UrlSuffixStoryCreators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/events.
        /// </summary>
        internal static string UrlSuffixStoryEvents {
            get {
                return ResourceManager.GetString("UrlSuffixStoryEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stories/{0}/series.
        /// </summary>
        internal static string UrlSuffixStorySeries {
            get {
                return ResourceManager.GetString("UrlSuffixStorySeries", resourceCulture);
            }
        }
    }
}
